### ISSUE TITLE
Discussion: Adding custom Fire mode graphics for multi-barrel shot weapons

### ISSUE THREAD

**Issue by zozilin** [CombatExtendedRWMod/CombatExtended#1034]
@Alicecomma As discussed, it was mentioned that this feature can be implemented better.
9c8d2561a14e52a6c4a239486c76908bf854465a
7b01752f101645568d5d60f3cfd2c6d6623d954a

**Comment by Alicecomma** [comment]
The problem with making ammo consumed per shot a weapon-specific thing, is that it's impossible to have one weapon fire multiple types of projectiles with varying amounts of ammo per shot. The feature is preferably ammoset-specific instead.

**Comment by Alicecomma** [comment]
The feature could be added in many places:

- Gun ThingDef
- - statBases; However, there is likely no need to modify this property of guns (add additional barrels.. somehow)
- - Properties; However, modifying this is annoying
- - AmmoUser: One of the more logical places to modify
- - FireModes: Again more logical. Having a fire mode which fires two shells, thus uses two projectiles, within the same tick would prevent the need for AmmoUser and many forms of explanation within the info menu. Displaying a double-barrel weapon as FireMode would help this option significantly
- - weaponTags: Outdated method of changing properties, and does not solve the issue by itself

Implementing synchronously firing double-barreled shotguns is best performed using a new FireMode. This would allow switching modes to single-fire and has greatest explaining power to the player. AmmoUser is a second choice, because the presence of double-fire mechanics would need to be explained with more words and statistics.

----

- AmmoSetDef
- - <ammo>: The tag could be simply coded to the form "<n*ammo>" with n by default equal to 1 and possible to be set. This is the more easily implemented method from a third party standpoint, provided they know about AmmoSetDef and notice the use of e.g "2*" in front of a def - not every third party would notice this immediately.

----

- Projectile ThingDef
- - projectile: This already contains such variables as <pelletCount>, so the addition of a <ammoCost> variable is viable. This would require a custom projectile ThingDef, a custom AmmoSetDef and a custom reference to the def in the gun. Therefore, from a modding standpoint it is more work, although the benefits are greater customization. A gun could fire 3x, 2x or 1x charge cells for projectiles of varying power. This would require implementing a better UI for choosing amount of projectiles fired within a single AmmoCategory, although this is possible to do.

**Comment by Alicecomma** [comment]
Suggestion is therefore as follows:
- Handle synchronous fire in a NEW FireMode. The FireMode compProperties could set amount of rounds fired at once, the gizmo could display this property of the weapon (along with amount of ammo fired per shot).
- Handle energy weapons in a different, more involved way. Energy weapons should fire one shot but use up additional ammo - although this should change the warmup, cooldown, projectile speed/damage, etcetera, and should be controllable by the player to some extent. Implementing this feature is outside of the scope of what the current feature attempts to accomplish (firing double-barrel shotguns synchronously).

**Comment by Alicecomma** [comment]
Just something interesting to note, you can already do this without adding any new fire modes:
- set VerbProperties.ticksBetweenBurstShots = -1
- DO NOT add VerbProperties.burstShotCount (unless you want to have auto-fire as well as burst-fire. In that case, set burstShotCount = 2 or larger)
- set CompProperties_FireModes.noSingleShot = true (or false if you want to allow synchronous as well as asynchronous double-barrel firing)
- set aiUseBurstMode = true (or not, if you don't want enemies to use synchronous double fire)
- set aimedBurstShotCount = 2

**Comment by Alicecomma** [comment]
At its simplest, the FireModes could recognize when ticksBetweenBurstShots == -1 and burstShotCount > 2 and display a different FireMode graphic under those circumstances.
