### ISSUE TITLE
Vanilla Factions Expanded - Medieval Patch possible typo

### ISSUE THREAD

**Issue by usagirei** [CombatExtendedRWMod/CombatExtended#1184]
A `Vanilla Factions Expanded - Medival` patch will worm its way in if you have `Vanilla Weapons Expanded` installed

https://github.com/CombatExtendedRWMod/CombatExtended/blob/d3836b01d8caeda4b0f002dd12943527648618ea/Patches/Vanilla%20Factions%20Expanded%20-%20Medieval/ThingDef_Misc/VanillaMedieval_Ranged.xml#L4-L7

Should probably be referencing `Vanilla Factions Expanded - Medieval` instead like its sibling patches

https://github.com/CombatExtendedRWMod/CombatExtended/blob/d3836b01d8caeda4b0f002dd12943527648618ea/Patches/Vanilla%20Factions%20Expanded%20-%20Medieval/ThingDef_Misc/VanillaMedieval_Items.xml#L4-L7

**Comment by N7Huntsman** [comment]
Yep, good eye. As it happens, I was working on the Vanilla Weapons Expanded patch the other day and happened to notice this, so a fix is in a pending PR. 

Thank you for bringing it up, though! A lot of times, we come minor across issues like this that've existed for a long time because the people who notice them don't say anything.
